/** Etiquetas legibles de los tipos de estímulo (compartidas por dashboard y detalle de actividad). */
export const STIMULUS_LABELS: Record<string, string> = {
  gym: "Gimnasio",
  flexibility: "Flexibilidad",
  z2: "Z2 · Base",
  hiit_genuino: "HIIT",
  ronnestad_30_15: "Rønnestad 30/15",
  z2_sprints: "Z2 + sprints",
  z2_progressive: "Z2 progresivo",
  endurance_tempo: "Tempo en bloques",
  long_durability: "Salida larga + esfuerzo final",
  torque_low_cadence: "Torque a cadencia baja",
  over_under: "Over-unders",
  vo2_long: "VO2max largo 5′",
  sprint_neuro: "Sprints cortos",
  billat_30_30: "Billat 30-30",
  rst: "RST",
  sweet_spot: "Sweet spot",
  umbral: "Umbral",
  ftp_test: "Test de FTP (20 min)",
  ftp_test_8min: "Test de FTP (8 min)",
  ftp_test_5min: "Test de FTP (5 min)",
  other: "Otro",
};

export const ZONE_LABELS: Record<string, string> = {
  Z1: "Z1 Recuperación",
  Z2: "Z2 Resistencia",
  Z3: "Z3 Tempo",
  SS: "Sweet spot",
  Z4: "Z4 Umbral",
  Z5: "Z5 VO2max",
  Z6: "Z6 Anaeróbico",
  Z7: "Z7 Neuromuscular",
};
